{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "moodle.serviceAccountName" . }}
  labels:
{{ include "moodle.labels" . | indent 4 }}
{{- end -}}
